# Generated by Django 3.2.6 on 2021-09-10 14:53

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del origen')),
                ('short_name', models.CharField(max_length=10, verbose_name='Nombre corto del origen')),
                ('link', models.URLField(max_length=300, verbose_name='URL del origen')),
                ('color_hex', models.CharField(default='#ffffff', max_length=7, verbose_name='Color del origen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado')),
            ],
            options={
                'verbose_name': 'origen',
                'verbose_name_plural': 'origenes',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='Slug')),
                ('lead', models.TextField(max_length=500, verbose_name='Bajada')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Cuerpo')),
                ('link_source', models.URLField(max_length=500, verbose_name='URL de la fuente')),
                ('link_image', models.URLField(blank=True, max_length=300, verbose_name='URL de la imagen')),
                ('date', models.DateField(verbose_name='Fecha de la noticia')),
                ('featured', models.IntegerField(choices=[(0, 'No destacada'), (1, 'Destacada')], default=0, verbose_name='Noticia Destacada')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('id_origin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='news.origin', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-date'],
            },
        ),
    ]
