# Generated by Django 3.2.7 on 2021-09-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origin',
            options={'ordering': ['-name'], 'verbose_name': 'fuente', 'verbose_name_plural': 'fuentes'},
        ),
    ]
