# Generated by Django 3.2.7 on 2021-09-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created'], 'verbose_name': 'miembro del equipo', 'verbose_name_plural': 'miembros del equipo'},
        ),
    ]
