# Generated by Django 3.2.7 on 2021-09-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_position_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_position_alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Cargo'),
        ),
    ]
